### PR TITLE
P1370: Add first draft of numeric_limits experiences paper

### PR DESCRIPTION
**Pull request by mhoemmen**
@dalg24 This is the original version of the paper that I sent you.  I have not yet made revisions.  Thanks!

### CODE REVIEW

**Comment by mhoemmen** [comment]
@dalg24 , I just pushed one more commit with Sandia's funding statement and disclaimer.

**Comment by crtrott** [comment]
is this still relevant?

**Comment by dalg24** [comment]
This paper was a response to http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0437r1.pdf

Walter proposed wording for the numeric traits with the changes we suggested
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1841r1.pdf

I think we should merge as is

**Comment by mhoemmen** [comment]
LEWG reviewed some other paper recently that relates to this, if I remember right.

**Pull request merged**
