### PR TITLE
P0009: Put "exposition only" comments in italics

### PR DESCRIPTION
**Pull request by mhoemmen**

### CODE REVIEW

**Comment by dhollman** [comment]
I think it does. You just have to use html code blocks directly instead of the backticks. Bikeshed lets you mix html and markdown.

**Comment by mhoemmen** [comment]
@dhollman Let me see if I can figure that out....

**Comment by mhoemmen** [comment]
The `<xmp>` tag (otherwise easier to use, since it doesn't require escaping less-thans) has the same issue:
```
<xmp highlight="c++">
std::vector<int> foo (42); // *exposition only*
</xmp>
```

**Comment by mhoemmen** [comment]
I tried replacing the asterisks with `<em> ... </em>` or `<i> ... </i>`; no luck.

**Comment by mhoemmen** [comment]
Oh wait, I got it!  This works:
```
<pre highlight="c++">
std::vector&lt;int> foo (42); // <i>foo</i>
</pre>
```

**Comment by mhoemmen** [comment]
Yup, it has to be `<pre>`, not `<xmp>`.  This will take a while to fix....

**Pull request closed without merging**
