### PR TITLE
Update P0009.md

### PR DESCRIPTION
**Pull request by mhoemmen**
@crtrott @dalg24 @nliber 

For justification, please see today's (2022/06/22) discussion with Walker, and the following Compiler Explorer example:

https://godbolt.org/z/vrqhacqxo

### CODE REVIEW

**Comment by mhoemmen** [comment]
I tried this out in the actual implementation, and it doesn't work: https://godbolt.org/z/E4G9xfehc

Search for `NEW_MDSPAN_DEDUCTION_GUIDES`.  Neither the current code nor the new code correctly deduces from `char[3]`.

**Comment by mhoemmen** [comment]
The implementation's deduction guides differ a bit from P0009's.  I changed the code and still didn't get it to work:

https://godbolt.org/z/aPr3jTPTz

**Comment by mhoemmen** [comment]
Christian and I worked it out tonight.

**Comment by crtrott** [comment]
https://godbolt.org/z/crcEzYn13

I think we have it almost right just need to take const Pointer& in the deduction guide. 

Note we do NOT want to deduce from std::move(carray) because thats dangling immediately (we never store a carray, we get a ptr to the array ...). We also don't want to deduce anything from multi-dimensional carrays, since folks would likely expect a 2d-mdspan, but we can't make a 2d mdspan because of the aliasing rules.

**Comment by crtrott** [comment]
FYI: the implementation (which as of right now still needs an extra define in order to enable P2554 behavior) actually had it as const Pointer& and thus it did work. I also checked, and we did have most of the tests we would think we should have (again required the define being externally set during build). Closing this.

**Comment by crtrott** [comment]
https://godbolt.org/z/6ejvY5Yxz

That is the link with the current mdspan impl, which works as expected.

**Pull request closed without merging**
