### PR TITLE
P1673R6 changes

### PR DESCRIPTION
**Pull request by mhoemmen**
Changes for P1673R6.

### CODE REVIEW

**Comment by crtrott** [comment]
I don't think we should remove the overloads without alpha, its not ambiguous at all if you use the correct requires clauses.

**Review by crtrott — CHANGES_REQUESTED** [review]
I don't think we should remove the overloads - at least not without talking to all the other authors. There is no ambiguity here if you use the correct preconditions (i.e. C++20 requires clauses).

**Comment by mhoemmen** [comment]
> I don't think we should remove the overloads - at least not without talking to all the other authors. There is no ambiguity here if you use the correct preconditions (i.e. C++20 requires clauses).

I'll put them back in the next version.  That was a bit of a hasty decision.  On the other hand, the ambiguity would be challenging to resolve without some complicated `requires` clauses, and I'm not sure if LEWG would appreciate the lack of precedent. 

In any case, I submitted this as R6, so please do merge it.  I can file an issue to bring back the overloads, if we can figure out how to constrain them correctly.

**Comment by mhoemmen** [comment]
Superseded by PR https://github.com/ORNL/cpp-proposals-pub/pull/222 .  Thanks!

**Comment by mhoemmen** [comment]
Merge of https://github.com/ORNL/cpp-proposals-pub/pull/222 means we can delete this branch.

**Pull request closed without merging**
