### PR TITLE
P1673R2: Pre-Cologne 2020 final submitted version

### PR DESCRIPTION
**Pull request by mhoemmen**
@crtrott @dalg24 @dhollman and friends :-)

I made a couple minor formatting changes and fixed the submission date.  This is the final version that I uploaded and submitted for the pre-Cologne 2020 mailing.

### CODE REVIEW

**Comment by dalg24** [comment]
I don't have the permission to merge :/

**Comment by mhoemmen** [comment]
@dalg24 thanks for approving, though!

**Comment by crtrott** [comment]
is this still relevant? I guess the one I just merged was the only one we needed right?

**Comment by mhoemmen** [comment]
@crtrott If it doesn't merge into the main branch, we might like to make a separate branch or tag for it.  It looks like there are merge conflicts.

**Comment by crtrott** [comment]
Is the solve/product change correct? It looks like the other stuff wasn't changed yet but probably should? The date is the conflict.

**Pull request closed without merging**
